### PR TITLE
vendor: volla: audio: Fix tags

### PR DESCRIPTION
**Pull request by Roker2**
image

### CODE REVIEW

**Comment by techyminati** [comment]
Hi can you explain this patch?

What does this improve/change. 

Thanks

**Comment by Roker2** [comment]
> Hi can you explain this patch?
> 
> What does this improve/change.
> 
> Thanks

For example check ringtones list in settings of Volla OS. You will find `volla_ringtone`. I think it is not beautiful. Android can use media tag "name" for showing ringtone name.

Result of this patch is `Volla ringtone` label is in ringtones list.

**Comment by Roker2** [comment]
@techyminati, hi! Any updates?

**Comment by techyminati** [comment]
@Roker2 , Can you push this change on volla-12.1 branch?

**Review by techyminati — CHANGES_REQUESTED** [review]
should be pushed on volla-12.1 branch

**Comment by Roker2** [comment]
Done.

**Review by techyminati — APPROVED** [review]
Looks good

**Comment by techyminati** [comment]
Merged, thanks for your contribution.

**Pull request merged**
